# SPDX-FileCopyrightText: 2026 Alexander Gomez
# SPDX-License-Identifier: Apache-2.0
"""``manifest.yaml`` — the tracked half of ``datasets/tier0-synthetic/``.

Shape follows the required-fields table in ``datasets/README.md`` ("manifest.yaml
— the contract"): ``name``, ``tier``, ``version``, ``source``, ``licence``,
``ground_truth``, ``files[]`` (``path``, ``sha256``, ``sample_rate``, ``channels``,
``bit_depth``, ``duration``), ``preprocessing``, ``use``, ``restrictions``,
``clinical_claim`` (always the quoted string ``"no"``, ADR 0005 rule 4). ``path``
is relative to the manifest's own directory, so ``--out`` can point anywhere.

``version`` is ``git describe --tags --dirty`` of the generator's checkout, or
``unreleased`` when no tag is reachable; the short commit is recorded separately
under ``generator``. Both are INFORMATIONAL: the manifest is written before the
commit that lands it, so ``commit`` names the previous HEAD (with ``-dirty``
when the generator itself was uncommitted at the time) and can never name the
commit it sits in. Neither takes part in :func:`check` — the sha256 per file
does; the generator code that those bytes depend on is pinned by the package
``uv.lock`` and by git, not by this field.

Not a CLI module; :mod:`synth_signals.cli` drives :func:`build_manifest`,
:func:`write` and :func:`check`.
"""

from __future__ import annotations

import hashlib
import platform
import subprocess
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import scipy
import yaml

from . import __version__, catalogue, wavio

MANIFEST_NAME = "manifest.yaml"
DATASET_NAME = "tier0-synthetic"

HEADER = """\
# SPDX-FileCopyrightText: 2026 Alexander Gomez
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by python-scripts/synth_signals -- do not edit by hand.
#   cd python-scripts/synth_signals
#   uv run python -m synth_signals generate --out ../../datasets/tier0-synthetic
#   uv run python -m synth_signals check    --out ../../datasets/tier0-synthetic
#
# This file is the tracked half of the dataset; the WAVs next to it are
# gitignored (datasets/**/*.wav) and regenerated. `check` regenerates every
# entry in memory and fails on any sha256 that differs from the one recorded
# here, which makes this file the reproducibility oracle for the generator
# (and, through numpy/scipy/libm, for the machine -- see the package docstring).
# Paths are relative to this file.
"""


def _git(args: list[str], cwd: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True, check=True, timeout=10
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    return out or None


def version_string(repo_dir: Path | None = None) -> tuple[str, str | None]:
    """``(version, commit)``: ``git describe --tags --dirty`` or ``unreleased``; short sha or ``None``."""
    cwd = repo_dir or Path(__file__).resolve().parent
    described = _git(["describe", "--tags", "--dirty"], cwd)
    commit = _git(["rev-parse", "--short", "HEAD"], cwd)
    if commit and _git(["status", "--porcelain", "--untracked-files=no"], cwd):
        commit += "-dirty"
    return (described or "unreleased"), commit


def environment() -> dict[str, Any]:
    version, commit = version_string()
    return {
        "package": "python-scripts/synth_signals",
        "package_version": __version__,
        "commit": commit,
        "python": platform.python_version(),
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "platform": f"{platform.system()} {platform.machine()}",
    }


def build_manifest(builts: Iterable[catalogue.Built]) -> dict[str, Any]:
    builts = list(builts)
    version, _ = version_string()
    truths = {b.entry.name: catalogue.ground_truth(b) for b in builts}
    files = [
        {
            "path": b.filename,
            "sha256": b.sha256,
            "sample_rate": b.entry.fs,
            "channels": wavio.CHANNELS,
            "bit_depth": wavio.BIT_DEPTH,
            "duration": b.entry.dur_s,
        }
        for b in builts
    ]
    return {
        "name": DATASET_NAME,
        "tier": 0,
        "version": version,
        "source": {
            "generator": "python-scripts/synth_signals (Apache-2.0); per-file parameters under ground_truth",
            "command": "python -m synth_signals generate --out datasets/tier0-synthetic",
            "environment": environment(),
        },
        "licence": {
            "spdx": "Apache-2.0",
            "terms": "generated in-repo under the repository LICENSE; no upstream terms, nothing to fetch",
        },
        "ground_truth": {
            "kind": "exact by construction",
            "format": "per file below: generator, parameters, derived values; bins quoted for N = 4096 at 32 kHz",
            "files": truths,
        },
        "files": files,
        "preprocessing": "none",
        "use": {
            "path": "digital injection only (mic bypassed); Tier 0 never makes an acoustic-path claim",
            "rows": "per file under ground_truth.files.<name>.use; golden set tier0-synthetic (ADR 0009, host/golden/)",
        },
        "restrictions": "none",
        "clinical_claim": "no",
    }


def dump(manifest: dict[str, Any]) -> str:
    body = yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True, width=100, default_flow_style=False)
    return HEADER + body


def write(out_dir: Path, manifest: dict[str, Any]) -> Path:
    path = Path(out_dir) / MANIFEST_NAME
    path.write_text(dump(manifest), encoding="utf-8")
    return path


def load(out_dir: Path) -> dict[str, Any]:
    path = Path(out_dir) / MANIFEST_NAME
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict) or data.get("name") != DATASET_NAME or "files" not in data:
        raise ValueError(f"{path}: not a {DATASET_NAME} manifest")
    if data.get("clinical_claim") != "no":
        raise ValueError(f"{path}: clinical_claim must be the string 'no' (ADR 0005 rule 4)")
    return data


# --- check ------------------------------------------------------------------


@dataclass(frozen=True)
class Finding:
    name: str
    kind: str  # "ok" | "drift" | "disk-mismatch" | "absent" | "missing-in-manifest" | "unknown-in-manifest"
    detail: str = ""

    @property
    def failed(self) -> bool:
        return self.kind not in ("ok", "absent")


def check(out_dir: Path, names: Iterable[str] | None = None) -> list[Finding]:
    """Regenerate in memory and compare against the manifest (and the disk, where a file exists).

    * ``drift`` — regenerated bytes hash differently from the manifest (generator,
      numpy/scipy or libm changed);
    * ``disk-mismatch`` — the file on disk hashes differently from the manifest
      (stale or corrupted; regenerate);
    * ``absent`` — not on disk (gitignored; not a failure, ``generate`` writes it);
    * ``missing-in-manifest`` / ``unknown-in-manifest`` — catalogue and manifest
      disagree on the set of names.
    """
    out_dir = Path(out_dir)
    data = load(out_dir)
    recorded = {f["path"]: f for f in data["files"]}
    wanted = list(names) if names is not None else list(catalogue.NAMES)
    findings: list[Finding] = []
    for name in wanted:
        entry = catalogue.by_name(name)
        built = catalogue.build(entry)
        rec = recorded.get(built.filename)
        if rec is None:
            findings.append(Finding(name, "missing-in-manifest"))
            continue
        if rec["sha256"] != built.sha256:
            findings.append(Finding(name, "drift", f"manifest {rec['sha256'][:12]}… regenerated {built.sha256[:12]}…"))
            continue
        on_disk = out_dir / built.filename
        if not on_disk.exists():
            findings.append(Finding(name, "absent"))
            continue
        disk_sha = hashlib.sha256(on_disk.read_bytes()).hexdigest()
        if disk_sha != rec["sha256"]:
            findings.append(Finding(name, "disk-mismatch", f"manifest {rec['sha256'][:12]}… disk {disk_sha[:12]}…"))
            continue
        findings.append(Finding(name, "ok"))
    if names is None:
        for path in recorded:
            if path.removesuffix(".wav") not in catalogue.NAMES:
                findings.append(Finding(path, "unknown-in-manifest"))
    return findings


def print_findings(findings: list[Finding], stream=sys.stdout) -> bool:
    width = max((len(f.name) for f in findings), default=1)
    for f in findings:
        stream.write(f"{f.name:<{width}}  {f.kind}{('  ' + f.detail) if f.detail else ''}\n")
    failed = [f for f in findings if f.failed]
    stream.write(f"{len(findings) - len(failed)}/{len(findings)} ok, {len(failed)} failed\n")
    return not failed
