# SPDX-FileCopyrightText: 2026 Alexander Gomez
# SPDX-License-Identifier: Apache-2.0
"""Shared fixtures: where the repository and the first golden set are.

The golden set is read as data from ``host/golden/outputs/tier0-synthetic/``
(GPL side, files only). Tests that need it skip when it is not on disk — a
fresh checkout before the ``golden:`` commit that carries it — and say so.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
GOLDEN_FILES_MD = REPO_ROOT / "docs" / "validation" / "golden-files.md"
TIER0_MANIFEST = REPO_ROOT / "host" / "golden" / "outputs" / "tier0-synthetic" / "manifest.yaml"


@pytest.fixture(scope="session")
def repo_root() -> Path:
    assert (REPO_ROOT / "CLAUDE.md").is_file(), f"not the repository root: {REPO_ROOT}"
    return REPO_ROOT


@pytest.fixture(scope="session")
def golden_files_md(repo_root: Path) -> Path:
    assert GOLDEN_FILES_MD.is_file(), f"tolerance table missing: {GOLDEN_FILES_MD}"
    return GOLDEN_FILES_MD


@pytest.fixture(scope="session")
def tier0_manifest_path(repo_root: Path) -> Path:
    if not TIER0_MANIFEST.is_file():
        pytest.skip(f"first golden set not on disk: {TIER0_MANIFEST} (generated by B-U6, committed as `golden:`)")
    return TIER0_MANIFEST
