# SPDX-FileCopyrightText: 2026 Alexander Gomez
# SPDX-License-Identifier: GPL-3.0-or-later
"""`spectral-web peak` — the founding document's M0, by hazard (roadmap W0's ≤ 3 cents gate).

The gate, from the roadmap: "`spectral-web peak` reports the Tier-0 1 kHz
file's peak within **≤ 3 cents** (the peak-frequency row of
docs/validation/README.md)". It is asserted here twice — once through the
library function and once through the actual command line, because the number
the row is about is the one that gets *printed*.

The hazards, one test each:

  * **The conventions drift.** A window built by name instead of from
    coefficients (`get_window("hann")` is the SYMMETRIC form), a second
    1/32768, a `norm="ortho"` transform — any of them moves the level and some
    of them move the frequency. The path runs through
    `spectrum.reference_spectrum` and nothing else, and the level of a −20 dBFS
    tone is asserted alongside its frequency.
  * **The interpolation does nothing.** A parabola that silently returns the
    bin centre would still pass the 1 kHz case, because 1000 Hz at fs = 32 kHz
    and N = 4096 lands EXACTLY on bin 128 (1000 / 7.8125 = 128.0). So the
    off-bin file is tested too: 440 Hz sits at bin 56.32, where the raw bin
    centre is −9.86 cents out and only interpolation reaches the row.
  * **The audio callback does work.** Allocation, I/O or a per-sample loop in
    the callback is what makes a live capture drop blocks. Asserted by
    booby-trapping every numpy array constructor for the duration of a
    callback and by checking the ring buffer's memory address is unchanged.
  * **A missing PortAudio produces a traceback.** Without the `capture` extra
    the CLI must exit **2** with the exact `uv sync` line, the same convention
    `spectral-golden` uses.

The live-capture tests inject a FAKE `sounddevice` through `sys.modules`: this
machine's CI has no sound card, and a test that needed one would be a test that
is skipped exactly when it matters.

Run: `uv run --project host pytest -q host/tests/test_web_peak.py`
"""

from __future__ import annotations

import importlib.machinery
import re
import sys
import types

import numpy as np
import pytest

from spectral_host import spectrum
from spectral_host.capture import peak as peak_mod
from spectral_host.web import cli
from spectral_host.web.extras import EXTRAS

FS = 32000

#: The roadmap's row: the interpolated peak of the Tier-0 1 kHz file, in cents.
CENTS_GATE = 3.0

#: `<f> Hz  (bin k, <level> dBFS)` — the founding document's M0 line.
PEAK_LINE = re.compile(r"^(?P<hz>[-\d.]+) Hz  \(bin (?P<bin>\d+), (?P<db>[-\d.]+) dBFS\)")


def tier0_wav(tier0_dir, name: str):
    """A Tier-0 WAV, asserted present — never skipped.

    A skipped golden test in CI is exactly the silent green ADR 0009 exists to
    prevent (`conftest.tier0_dir`). The WAVs are gitignored and regenerated by
    the Apache-2.0 generator; the command is in the message.
    """
    path = tier0_dir / name
    assert path.is_file(), (
        "%s is missing. The Tier-0 WAVs are gitignored; regenerate them with:\n"
        "  cd python-scripts/synth_signals && uv run python -m synth_signals generate "
        "--out ../../datasets/tier0-synthetic" % path
    )
    return path


def parse(line: str) -> tuple[float, int, float]:
    match = PEAK_LINE.match(line.strip())
    assert match, "unparsable reading: %r" % line
    return float(match["hz"]), int(match["bin"]), float(match["db"])


# --- the gate ------------------------------------------------------------------------


def test_the_tier0_1khz_file_reads_within_three_cents(tier0_dir):
    """Roadmap W0's definition-of-done row, through the library."""
    path = tier0_wav(tier0_dir, "sine_1000_m20dBFS_32k.wav")
    reading = next(peak_mod.wav_peaks(path, spectrum.ADR_0006_DEFAULT, hop=4096, limit=1))
    error = peak_mod.cents(reading.frequency_hz, 1000.0)
    assert abs(error) <= CENTS_GATE, "%.6f Hz is %.3f cents from 1000 Hz" % (reading.frequency_hz, error)
    # The conventions, in the same breath: a −20 dBFS full-scale-sine reference
    # (ADR 0006 D3) reads −20 dBFS, and the S1 power spectrum is what makes it.
    assert reading.level_dbfs == pytest.approx(-20.0, abs=0.05)


def test_the_cli_prints_the_tier0_1khz_peak_within_three_cents(tier0_dir, capsys):
    """The same row through the actual command line — the printed number is the one the row is about."""
    path = tier0_wav(tier0_dir, "sine_1000_m20dBFS_32k.wav")
    status = cli.main(["peak", "--wav", str(path), "--once", "--reference", "1000"])
    assert status == 0
    out = capsys.readouterr()
    hz, bin_index, level = parse(out.out.splitlines()[0])
    assert abs(peak_mod.cents(hz, 1000.0)) <= CENTS_GATE
    assert bin_index == 128, "1000 Hz at fs = 32 kHz, N = 4096 is bin 1000/7.8125 = 128"
    assert level == pytest.approx(-20.0, abs=0.05)
    assert "cents re 1000 Hz" in out.out
    # The configuration line goes to stderr so stdout stays a column of readings.
    assert out.err.startswith("# ")


def test_the_off_bin_file_needs_the_interpolation_to_reach_the_row(tier0_dir):
    """440 Hz sits at bin 56.32: the bin centre is −9.86 cents out, so this case fails without interpolation."""
    path = tier0_wav(tier0_dir, "sine_440_m20dBFS_32k.wav")
    reading = next(peak_mod.wav_peaks(path, spectrum.ADR_0006_DEFAULT, hop=4096, limit=1))
    assert reading.bin_index == 56
    bin_centre = 56 * FS / 4096
    assert abs(peak_mod.cents(bin_centre, 440.0)) > CENTS_GATE, "the uninterpolated answer must be OUT of the row"
    assert abs(peak_mod.cents(reading.frequency_hz, 440.0)) <= CENTS_GATE


def test_the_interpolation_is_a_no_op_at_an_edge_or_a_non_peak():
    """A flat or rising triple is not a peak; extrapolating from one would move the answer away from the data."""
    levels = np.array([-10.0, -20.0, -30.0, -40.0])
    assert peak_mod.interpolate_peak(levels, 0) == (0.0, -10.0)
    assert peak_mod.interpolate_peak(levels, levels.size - 1) == (0.0, -40.0)
    flat = np.array([-10.0, -10.0, -10.0])
    assert peak_mod.interpolate_peak(flat, 1) == (0.0, -10.0)


def test_a_wav_is_read_at_its_own_rate_and_the_header_says_so(tier0_dir, capsys):
    """A 48 kHz file is read at 48 kHz — the rate comes from the FILE, never from a default that was left over.

    The header line has to carry that same rate. It quoted `--rate`'s default
    (32000, bin 7.8125 Hz) while the transform ran at 48000 (bin 11.71875 Hz)
    until this was fixed: the printed bin width described a spectrum nobody
    computed, which is the "bin_width_hz is fiction" failure ADR 0021 decision
    7(c) is written against.
    """
    path = tier0_wav(tier0_dir, "sine_440_m20dBFS_48k.wav")
    reading = next(peak_mod.wav_peaks(path, spectrum.ADR_0006_DEFAULT, hop=4096, limit=1))
    assert abs(peak_mod.cents(reading.frequency_hz, 440.0)) <= CENTS_GATE

    assert cli.main(["peak", "--wav", str(path), "--once"]) == 0
    header = capsys.readouterr().err.splitlines()[0]
    assert "fs=48000 Hz" in header, header
    assert "bin=11.7188 Hz" in header, header
    # `--interval-ms` is a duration: its hop follows the file's rate, not --rate's.
    assert "hop=4800" in header, header


def test_a_wav_at_a_rate_the_preset_does_not_name_is_refused(tier0_dir, capsys):
    """ADR 0021 decision 7(c) on the file path, as `live_peaks` applies it on the device: reject, and name both rates.

    `live_singing` is 32 kHz. Analysing a 48 kHz file on its 640-sample hop
    would attribute a reading — and a 13.3 ms interval — to a preset that
    describes neither (ADR 0010 decision 7: validate and reject, never coerce).
    """
    path = tier0_wav(tier0_dir, "sine_440_m20dBFS_48k.wav")
    assert cli.main(["peak", "--wav", str(path), "--preset", "live_singing", "--once"]) == cli.EXIT_USAGE
    err = capsys.readouterr().err
    assert "48000" in err and "32000" in err, "both rates have to be named: %r" % err
    assert "Traceback" not in err


@pytest.mark.parametrize("flag,value", [("--rate", "48000"), ("--interval-ms", "50")])
def test_a_rate_or_interval_alongside_a_preset_is_refused(tier0_dir, capsys, flag, value):
    """`resolve_config`'s own rule. Both flags default to None so argparse can tell a typed value from a default."""
    path = tier0_wav(tier0_dir, "sine_1000_m20dBFS_32k.wav")
    status = cli.main(["peak", "--wav", str(path), "--preset", "live_singing", flag, value, "--once"])
    assert status == cli.EXIT_USAGE
    err = capsys.readouterr().err
    assert flag in err and "--preset" in err
    assert "Traceback" not in err


def test_a_preset_supplies_the_whole_configuration(tier0_dir, repo_root, capsys):
    """ADR 0021 decision 7: the CLI reads the same preset file the browser fetches, and takes all of it."""
    path = tier0_wav(tier0_dir, "sine_1000_m20dBFS_32k.wav")
    status = cli.main(["peak", "--wav", str(path), "--preset", "live_singing", "--once"])
    assert status == 0
    out = capsys.readouterr()
    hz, _bin, _level = parse(out.out.splitlines()[0])
    assert abs(peak_mod.cents(hz, 1000.0)) <= CENTS_GATE
    assert "preset live_singing" in out.err and "hop=640" in out.err, "interval_ms 20 at 32 kHz is a 640-sample hop"


# --- the ring and the callback ---------------------------------------------------------


def test_the_callback_allocates_nothing_and_does_no_io(capsys, monkeypatch):
    """The audio thread's rule: copy into a preallocated ring, and nothing else."""
    ring = peak_mod.SampleRing(4096)
    callback = peak_mod.make_callback(ring)
    address_before = ring.buffer.__array_interface__["data"][0]
    block = np.zeros((512, 1), dtype=np.int16)

    calls: list[str] = []
    for name in ("zeros", "empty", "array", "asarray", "ascontiguousarray", "concatenate", "frombuffer", "copy"):
        real = getattr(np, name)

        def trap(*args, _name=name, _real=real, **kwargs):  # pragma: no cover - failure path
            calls.append(_name)
            return _real(*args, **kwargs)

        monkeypatch.setattr(np, name, trap)

    callback(block, 512, None, None)

    assert calls == [], "the callback called numpy array constructors: %s" % calls
    assert ring.buffer.__array_interface__["data"][0] == address_before, "the ring buffer was reallocated"
    assert ring.written == 512
    captured = capsys.readouterr()
    assert captured.out == "" and captured.err == "", "the callback printed — that is I/O on the audio thread"


def test_the_ring_wraps_without_losing_the_most_recent_samples():
    """`latest(n)` must span the wrap; a ring that silently returned the pre-wrap half would read as a dead input."""
    ring = peak_mod.SampleRing(8)
    ring.push(np.arange(6, dtype=np.int16))
    ring.push(np.arange(6, 12, dtype=np.int16))
    assert list(ring.latest(4)) == [8, 9, 10, 11]
    assert ring.latest(9) is None, "more than the ring holds is None, never a short frame"


def test_the_ring_reports_nothing_until_a_full_frame_has_arrived():
    """A partial frame zero-padded to N would be a spectrum of a signal that was never there."""
    ring = peak_mod.SampleRing(1024)
    ring.push(np.zeros(100, dtype=np.int16))
    assert ring.latest(512) is None
    ring.push(np.zeros(500, dtype=np.int16))
    assert ring.latest(512) is not None


# --- live capture, through a fake sounddevice --------------------------------------------


def fake_sounddevice(tone_hz: float = 440.0, amplitude: int = 3000) -> types.ModuleType:
    """A `sounddevice` stand-in whose `InputStream` feeds ONE block of an int16 tone to the callback.

    `__spec__` is set because `extras.module_available` probes with
    `importlib.util.find_spec`, which consults `sys.modules` first and raises
    `ValueError` for a module whose spec is None — a fake without one would be
    reported as *absent* and the test would exercise the wrong path.
    """
    module = types.ModuleType("sounddevice")
    module.__spec__ = importlib.machinery.ModuleSpec("sounddevice", None)

    class InputStream:
        def __init__(self, samplerate, channels, dtype, blocksize, device, callback):
            assert dtype == "int16", "capture must be int16 so the 1/32768 seam is applied exactly once"
            assert channels == 1
            self.samplerate = samplerate
            self.blocksize = blocksize
            self.device = device
            self._callback = callback

        def __enter__(self):
            n = int(self.blocksize)
            t = np.arange(n) / float(self.samplerate)
            block = np.rint(amplitude * np.sin(2 * np.pi * tone_hz * t)).astype(np.int16).reshape(n, 1)
            self._callback(block, n, None, None)
            return self

        def __exit__(self, *exc):
            return False

    module.InputStream = InputStream
    return module


def test_live_capture_prints_a_frequency_within_one_bin_of_the_injected_tone(monkeypatch, capsys):
    """One block of a 440 Hz int16 tone in, one reading out — through the real CLI and the real DSP."""
    monkeypatch.setitem(sys.modules, "sounddevice", fake_sounddevice(440.0))
    status = cli.main(["peak", "--fft-size", "512", "--block", "512", "--rate", str(FS), "--once"])
    assert status == 0
    hz, _bin, _level = parse(capsys.readouterr().out.splitlines()[0])
    bin_width = FS / 512
    assert abs(hz - 440.0) <= bin_width, "%.3f Hz is more than one bin (%.3f Hz) from 440" % (hz, bin_width)


def test_live_capture_refuses_a_device_that_opened_at_another_rate(monkeypatch, capsys):
    """ADR 0021 decision 7(c) applied to the CLI: assert the rate, never resample it silently."""
    module = fake_sounddevice(440.0)
    real_stream = module.InputStream

    class WrongRate(real_stream):  # type: ignore[misc, valid-type]
        def __init__(self, **kwargs):
            super().__init__(**kwargs)
            self.samplerate = 48000  # what the device actually gave us

    module.InputStream = WrongRate
    monkeypatch.setitem(sys.modules, "sounddevice", module)
    status = cli.main(["peak", "--fft-size", "512", "--block", "512", "--rate", str(FS), "--once"])
    assert status == cli.EXIT_USAGE
    assert "48000" in capsys.readouterr().err


def test_without_the_capture_extra_the_cli_exits_two_with_the_install_line(monkeypatch, capsys):
    """`spectral-golden`'s convention: 2 means "this build cannot do what the command line asked"."""
    monkeypatch.delitem(sys.modules, "sounddevice", raising=False)
    monkeypatch.setattr(
        "spectral_host.web.extras.module_available",
        lambda name: False if name == "sounddevice" else True,
    )
    status = cli.main(["peak", "--fft-size", "512", "--once"])
    assert status == cli.EXIT_USAGE
    err = capsys.readouterr().err
    assert EXTRAS["capture"].install_hint in err
    assert "sounddevice" in err
    assert "Traceback" not in err
